# Smoke test configuration - minimal test to verify automation works

# Path to dataset file
dataset_file_path = "longmemeval-datasets/longmemeval_smoke.json"

# Vault configuration
vault_title = "longmemeval-smoke-test"

# Model configuration - using fast, cheap models for testing
[models]
ingest = "openrouter:openai/gpt-5-nano-2025-08-07"
qa = "openrouter:openai/gpt-5-nano-2025-08-07"

# Search configuration
[search]
use_two_pass = false  # Faster for smoke test

# Agent configuration
[agent]
context_only = true  # Use context-only mode for faster processing (default)

# Mycelian API configuration
[mycelian]
api_url = "http://localhost:11545/v0"
api_key = "LOCAL_DEV_MODE_NOT_FOR_PRODUCTION"
