# BA durable-fact smoke config

# Absolute path to dataset
dataset_file_path = "longmemeval-datasets/longmemeval_ba_smoke.json"

# Vault configuration
vault_title = "longmemeval-ba-smoke"

# Models (fast for iteration)
[models]
ingest = "openrouter:openai/gpt-5-nano-2025-08-07"
qa     = "openrouter:openai/gpt-5-nano-2025-08-07"

# Search config
[search]
use_two_pass = false

# Agent settings
[agent]
# Keep default context_only=true first to reproduce omission; flip to false to test entries
context_only = true

# Mycelian API
[mycelian]
api_url = "http://localhost:11545/v0"
api_key = "LOCAL_DEV_MODE_NOT_FOR_PRODUCTION"
